close all;

Common.clearClasses();
%clear all;
clc;

MySQL.mym('closeall');

category = 'test';
experimentName = 'numSamples';
numTrials = 2;
numIterations = 50;

configuredTask = Experiments.Tasks.ViaPoint();
configuredTask.addParameterSetter(@ParameterSettings.PathIntegralRewardSettings);
%%
configuredLearner = Experiments.Learner.StepBasedLearningSetup('PIREPS');

evaluationCriterion = Experiments.EvaluationCriterion();

evaluate = Experiments.Evaluation(...
    {'settings.numSamples', 'settings.maxSamples', 'settings.maxCorrActions', 'settings.entropyBeta', 'settings.Noise_std'},{...
    30, 30, 1.0, 1.0, 0.025; ...
    },numIterations,numTrials);

lambda = Experiments.Evaluation(...
    {'settings.PathIntegralCostActionMultiplier'},{...
    1.0; 0.1; 0.01;0.001; ...
    },numIterations,numTrials);


% learner = Experiments.Evaluation(...
%     {'learner'},{...
%     @Learner.StepBasedRL.StepBasedRLPower; ...
%     },numIterations,numTrials);
learner = Experiments.Evaluation(...
    {'learner'},{...
    @Learner.StepBasedRL.StepBasedPIREPSLambda.CreateFromTrial; ...
    },numIterations,numTrials);
% learner = Experiments.Evaluation(...
%     {'learner'},{...
%     @Learner.StepBasedRL.StepBasedRLREPS; ...
%     },numIterations,numTrials);

evaluate = Experiments.Evaluation.getCartesianProductOf([evaluate, learner]);


experiment = Experiments.Experiment.createByName(experimentName, category, ...
    configuredTask, configuredLearner, evaluationCriterion, 5, ...
    {'127.0.0.1',1});

experiment.addEvaluation(evaluate);
experiment.startLocal();
%experiment.startRemote();
