close all;

Common.clearClasses();
%clear all;
clc;

MySQL.mym('closeall');

category = 'test';
experimentName = 'numSamples';
numTrials = 2;
numIterations = 400;

configuredTask = Experiments.Tasks.QuadLinkObstacleAvoidance();
configuredTask.addParameterSetter(@ParameterSettings.PathIntegralRewardSettings);

%%
configuredLearner = Experiments.Learner.StepBasedComposedTimeDependentLearningSetup('EpisodicPiREPS');

evaluationCriterion = Experiments.EvaluationCriterion();


evaluate = Experiments.Evaluation(...
    {'settings.maxCorrActions',  'settings.Noise_std', 'settings.initSigmaActions', 'settings.epsilonAction'},{...
    1.0, 0.5, 0.25, 0.6; ...
    },numIterations,numTrials);

numSamples = Experiments.Evaluation({'settings.numSamplesEpisodes', 'settings.maxSamples'}, {...
            1000 1000; 2000 2000; ...
            }, numIterations,numTrials);

lambda = Experiments.Evaluation(...
    {'settings.PathIntegralCostActionMultiplier'},{...
    1; 
    },numIterations,numTrials);

beta = Experiments.Evaluation(...
    {'settings.entropyBeta'},{...
    1.0; 
    },numIterations,numTrials);

% learner = Experiments.Evaluation(...
%     {'learner'},{...
%     @Learner.StepBasedRL.StepBasedRLPower; ...
%     },numIterations,numTrials);
learner = Experiments.Evaluation(...
    {'learner'},{...
    @Learner.EpisodicRL.EpisodicPIREPSLambda.CreateFromTrialForActionPolicy; ...
    },numIterations,numTrials);
% learner = Experiments.Evaluation(...
%     {'learner'},{...
%     @Learner.StepBasedRL.StepBasedRLREPS; ...
%     },numIterations,numTrials);

evaluate = Experiments.Evaluation.getCartesianProductOf([evaluate, learner, lambda, beta, numSamples]);


experiment = Experiments.Experiment.createByName(experimentName, category, ...
    configuredTask, configuredLearner, evaluationCriterion, 5, ...
    {'engelberger',2, 'lagrange', 2, 'pontyagrin', 2, 'phytagoras', 2});

experiment.addEvaluation(evaluate);
%experiment.startLocal();
experiment.startRemote();
