close all;

Common.clearClasses();
%clear all;
clc;

MySQL.mym('closeall');

category = 'test';
experimentName = 'numSamples';
numTrials = 10;
numIterations = 300;

configuredTask = Experiments.Tasks.PlanarReaching();

%%
configuredLearner = Experiments.Learner.TrajectoryBasedRewardModelLearningSetup ('ModelBaseREPSForReachingTaskWithoutNoiseDiffrentInitialSigma');

evaluationCriterion = Experiments.EvaluationCriterion();

%evaluator = Evaluator.ReturnEvaluatorEvaluationSamples();
%evaluationCriterion.registerEvaluator(evaluator);

standard = Experiments.Evaluation(...
    {'settings.numSamplesEpisodes', 'settings.numInitialSamplesEpisodes', ...
    'settings.maxSamples', 'settings.maxCorrParameters', ...
    'settings.rewardNoise', 'settings.numBasis', ...
    'settings.numJoints','settings.entropyBeta', ...
    'settings.numSamplesEpisodesVirtual','settings.epsilonAction','settings.numPara', ...
    'settings.bayesParametersSigma','settings.viaPointNoise','settings.numProjMat','settings.bayesNoiseSigma'},{...
    14,200,100, 1.0,  0.5, 5, 5,1,1000,1,7,1,0.0,1000,10^-2; ...
    },numIterations,numTrials);

standard2 = Experiments.Evaluation(...
    {'settings.initSigmaParameters'},{0.02;0.025;0.03;0.035;0.04;0.045;0.05},numIterations,numTrials);

% standard = Experiments.Evaluation(...
%     {'settings.numSamplesEpisodes', 'settings.numInitialSamplesEpisodes', ...
%     'settings.maxSamples', 'settings.maxCorrParameters', ...
%     'settings.rewardNoise', 'settings.numBasis', ...
%     'settings.initSigmaParameters', 'settings.numJoints','settings.entropyBeta', ...
%     'settings.numSamplesEpisodesVirtual','settings.epsilonAction','settings.numPara', ...
%     'settings.bayesParametersSigma','settings.viaPointNoise','settings.numProjMat'},{...
%     14, 100, 100, 1.0,  0.5, 5, 0.025,5,5,1000,1,2,10^-2,0.1,1000; ...
%     },numIterations,numTrials);
 learner = Experiments.Evaluation(...
     {'learner'},{...
     @Learner.EpisodicRL.EntropyREPS.CreateFromTrial; ...
     },numIterations,numTrials);

evaluate = Experiments.Evaluation.getCartesianProductOf([standard,standard2, learner]);


experiment = Experiments.Experiment.createByName(experimentName, category, ...
    configuredTask, configuredLearner, evaluationCriterion, 5, ...
    {'127.0.0.1',2});

experiment.addEvaluation(evaluate);
experiment.startLocal();
%experiment.startRemote();
