close all;

Common.clearClasses();
%clear all;
clc;

MySQL.mym('closeall');

category = 'test';
experimentName = 'initSigma';
numTrials = 3;
numIterations = 100;

configuredTask = Experiments.Tasks.ViaPoint();
configuredTask.addParameterSetter(@ParameterSettings.PathIntegralRewardSettings);

%%
configuredLearner = Experiments.Learner.StepBasedComposedTimeDependentLearningSetup('EpisodicPiREPS');

evaluationCriterion = Experiments.EvaluationCriterion();

evaluationCriterion.addCriterion('endLoop', 'data', 'states', Experiments.StoringType.STORE_PER_ITERATION, @(data)data.getDataEntry3D('states'));
evaluationCriterion.addCriterion('endLoop', 'data', 'actions', Experiments.StoringType.STORE_PER_ITERATION, @(data)data.getDataEntry3D('actions'));
evaluationCriterion.addCriterion('endLoop', 'data', 'rewards', Experiments.StoringType.STORE_PER_ITERATION, @(data)data.getDataEntry3D('rewards'));
evaluationCriterion.addCriterion('endLoop', 'data', 'finalRewards', Experiments.StoringType.STORE_PER_ITERATION, @(data)data.getDataEntry3D('finalRewards'));        

evaluate = Experiments.Evaluation(...
    {'settings.Noise_std', 'settings.initSigmaActions'},{...
     0.01, 0.05; ...
     0.01, 0.01; ...
     0.01, 0.005; ...
     0.01, 0.001; ...
    },numIterations,numTrials);

numSamples = Experiments.Evaluation({'settings.numSamplesEpisode', 'settings.maxSamples'}, {...
            800 800; ...
            }, numIterations,numTrials);

lambda = Experiments.Evaluation(...
    {'settings.PathIntegralCostActionMultiplier'},{...
    0.0001; 
    },numIterations,numTrials);

beta = Experiments.Evaluation(...
    {'settings.entropyBeta'},{...
    1.0; 
    },numIterations,numTrials);

% learner = Experiments.Evaluation(...
%     {'learner'},{...
%     @Learner.StepBasedRL.StepBasedRLPower; ...
%     },numIterations,numTrials);
learner = Experiments.Evaluation(...
    {'learner'},{...
    @Learner.EpisodicRL.EpisodicPIREPSLambda.CreateFromTrialForActionPolicy; ...
    },numIterations,numTrials);
% learner = Experiments.Evaluation(...
%     {'learner'},{...
%     @Learner.StepBasedRL.StepBasedRLREPS; ...
%     },numIterations,numTrials);

evaluate = Experiments.Evaluation.getCartesianProductOf([evaluate, learner, lambda, beta, numSamples]);


experiment = Experiments.Experiment.createByName(experimentName, category, ...
    configuredTask, configuredLearner, evaluationCriterion, 5, ...
    {'127.0.0.1',2});

experiment.addEvaluation(evaluate);
experiment.startLocal();
%experiment.startRemote();
