%close all;

%Common.clearClasses();
%clear all;
%clc;

%MySQL.mym('closeall');

category = 'test';
experimentName = 'test';
numTrials = 1;
numIterations = 1;

configuredTask = Experiments.Tasks.SwingUpTaskPeriodic(true);

%%
configuredLearner = Experiments.Learner.StepBasedRKHSREPS('RKHSREPSPeriodic');

% feature configurator
configuredFeatures = Experiments.Features.FeatureRBFKernelStatesPeriodicNew;
configuredPolicyFeatures = Experiments.Features.PolicyFeatureGenerator;
%configuredActionFeatures = Experiments.Features.FeatureRBFKernelActionsProdNew;
configureModelKernel = Experiments.Features.ModelFeatures;

% action policy configurator
configuredPolicy = Experiments.ActionPolicies.GaussianProcessPolicyConfiguratorNew;


evaluationCriterion = Experiments.EvaluationCriterion();



evaluationCriterion.registerEvaluator(Evaluator.ReturnEvaluatorEvaluationSamplesAverage());
%evaluationCriterion.registerEvaluator(Evaluator.SaveDataAndTrial());
% try 500 features
%nfeatures = 500;
mf = 1500; %max kernel features
safeatures = @(trial) FeatureGenerators.FourierKernelFeatures(trial.dataManager, trial.modelKernel, min(mf,trial.maxNumberKernelSamples), {{'states','actions'}}, '~stateactionFeatures');

evaluate = Experiments.Evaluation(...
     {'GPInitializer','GPLearnerInitializer','policyInputVariables','policyFeatureGenerator','modelLearner','stateFeatures','nextStateFeatures','settings.GPLearnerActions'},...
     {...
           @(dm, out, in,i) Distributions.Gaussian.GaussianLinearInFeaturesQuadraticCovariance(dm, out, in, 'BayesLinear'),... 
           @Learner.SupervisedLearner.BayesianLinearHyperLearnerCV...
           {'policyFeatures'},...%special policyFeatures? -> influences REPS if it is stateFeatures...?
            @(trial_) FeatureGenerators.FourierKernelFeatures(trial_.dataManager, copy(trial_.stateKernel), min(mf,trial_.maxNumberKernelSamples), 'states', '~policyFeatures'),...
            @(trial) Learner.ModelLearner.FeatureModelLearnernew(trial.dataManager, ...
              ':', trial.stateFeatures,...
              trial.nextStateFeatures,safeatures(trial)),...
            @(trial_) FeatureGenerators.FourierKernelFeatures(trial_.dataManager, trial_.stateKernel, min(mf,trial_.maxNumberKernelSamples), 'states', '~stateFeatures'),...
            @(trial_) FeatureGenerators.FourierKernelFeatures(trial_.dataManager, trial_.stateKernel, min(mf,trial_.maxNumberKernelSamples), 'nextStates', '~nextStateFeatures')...
            'GPStandard',... %unused in this case
         ;...
           @Kernels.GPs.GaussianProcess.CreateSquaredExponentialPeriodicGP,...
           @Kernels.Learner.GPHyperParameterLearnerCVTrajLikelihood.CreateWithStandardReferenceSet,...
           {'states'},...
           [],...
            @(trial) Learner.ModelLearner.RKHSModelLearnernew(trial.dataManager, ...
                ':', trial.stateFeatures,...
                trial.nextStateFeatures,trial.modelKernel),...
            @(trial_) Kernels.KernelBasedFeatureGenerator(trial_.dataManager, trial_.stateKernel, 'states', '~stateFeatures'),...
            @(trial_) Kernels.KernelBasedFeatureGenerator(trial_.dataManager, trial_.stateKernel, 'nextStates', '~nextStateFeatures'),...
            'GPStandard',...
           ;...
            @Kernels.GPs.GaussianProcess.CreateSquaredExponentialPeriodicGP,...
            @Kernels.Learner.GPHyperParameterLearnerCVTrajLikelihood.CreateWithStandardReferenceSet,...
            {'states'},...
            [],...
            @(trial) Learner.ModelLearner.FeatureModelLearnernew(trial.dataManager, ...
              ':', trial.stateFeatures,...
            trial.nextStateFeatures,safeatures(trial)),...
            @(trial_) Kernels.KernelBasedFeatureGenerator(trial_.dataManager, trial_.stateKernel, 'states', '~stateFeatures'),...
            @(trial_) Kernels.KernelBasedFeatureGenerator(trial_.dataManager, trial_.stateKernel, 'nextStates', '~nextStateFeatures'),...
            'GPSparse'...
     },numIterations,numTrials);
 


evaluate_nfeatures= Experiments.Evaluation(...
     {'settings.maxSizeReferenceSet','maxNumberKernelSamples',},...
     {...
        3000,3000;...
        500,500;...
        100,100;...
     },numIterations,numTrials);


evaluate.setDefaultParameter('useStateFeaturesForPolicy' , false);

evaluate.setDefaultParameter('settings.RKHSparams_V' , [-1e-2 -0.6 -5]);
evaluate.setDefaultParameter('settings.RKHSparams_ns' ,[-1e-2 -0.6 -5 -50] );
evaluate.setDefaultParameter('settings.tolSF',0.0001);
evaluate.setDefaultParameter('settings.epsilonAction' , 0.5);
evaluate.setDefaultParameter('settings.numSamplesEvaluation' , 100);
evaluate.setDefaultParameter('settings.GPVarianceNoiseFactorActions' ,1/sqrt(2) );
evaluate.setDefaultParameter('settings.GPVarianceFunctionFactor' ,1/sqrt(2) );
evaluate.setDefaultParameter('settings.HyperParametersOptimizerBayesLinearOptimizerActions','FMINUNC')
evaluate.setDefaultParameter('settings.HyperParametersOptimizerGaussianProcessActions','FMINUNC')
evaluate.setDefaultParameter('settings.HyperParametersOptimizerGPOptimizationActions','FMINUNC')

%what is the difference between these two?
%evaluate.setDefaultParameter('settings.maxSizeReferenceSet' , 3000);
%evaluate.setDefaultParameter('maxNumberKernelSamples', 3000);


%safeatures = @(trial) FeatureGenerators.FourierKernelFeatures(trial.dataManager, trial.modelKernel, nfeatures, {{'states','actions'}}, '~stateactionFeatures');
%evaluate.setDefaultParameter('modelLearner', @(trial) ...
%    Learner.ModelLearner.FeatureModelLearnernew(trial.dataManager, ...
%    ':', trial.stateFeatures,...
%    trial.nextStateFeatures,safeatures(trial)));
%evaluate.setDefaultParameter('stateFeatures', @(trial_) FeatureGenerators.FourierKernelFeatures(trial_.dataManager, trial_.stateKernel, nfeatures, 'states', '~stateFeatures'));            
%evaluate.setDefaultParameter('nextStateFeatures', @(trial_) FeatureGenerators.FourierKernelFeatures(trial_.dataManager, trial_.stateKernel, nfeatures, 'nextStates', '~nextStateFeatures'));
            
% evaluate.setDefaultParameter('GPInitializer', @Kernels.GPs.GaussianProcess.CreateSquaredExponentialPeriodicGP);
% evaluate.setDefaultParameter('GPLearnerInitializer', @Kernels.Learner.GPHyperParameterLearnerCVTrajLikelihood.CreateWithStandardReferenceSet);
% 







evaluate_all = Experiments.Evaluation.getCartesianProductOf([evaluate, evaluate_nfeatures]);



 
experiment = Experiments.Experiment.createByNameNew(experimentName, category, ...
    {configuredTask, configuredFeatures, configureModelKernel, configuredPolicyFeatures, ...
    configuredPolicy, configuredLearner}, evaluationCriterion, 5);

experiment.addEvaluation(evaluate_all);


experiment.startLocal();
%experiment.startBatch(20);

